[global]
db_url="localhost:26257/bidder"
prover_url=""

[chain]
chain_id=8453
chain_rpc="https://developer-access-mainnet.base.org"
blk_interval=2
blk_delay=1
max_blk_delta=5000
forward_blk_delay=500
brevis_market_addr="0x64A364888eeafc0F72e7788DD2fBEc9a456b305e"
prover_eth_addr=""
submitter_keystore=""
submitter_passphrase=""

[rule]
max_fee="10000000000"
max_input_size=0
prover_gas_price="20"
prove_min_duration=3600
vk_whitelist=[]
vk_blacklist=["0x0000000000000000000000000000000000000000000000000000000000000000"]