# common settings for all commands
[chain]
chain_id=8453
chain_rpc="https://developer-access-mainnet.base.org"
brevis_market_addr="0xcCec2a9FE35b6B5F23bBF303A4e14e5895DeA127"
staking_token_addr="0x086F405146Ce90135750Bbec9A063a8B20A8bfFb"
staking_controller_addr="0x9c0D8C5F10f0d3A02D04556a4499964a75DBf4A3"
market_viewer_addr="0x0ED8C6e128D1Be1e521B6AcDC25b348829a4Ffd2"

## user or prover keystore
keystore=""
passphrase=""

# for request-proof command, sample data as below
[[request]]
nonce=1767583814
vk="0x0018633ccc663a0fd37ddff9575230ceeb25f60c391c65c71e512b9afa1eaa67"
public_value_digest="0x1af2983076bc7f8a248617effe2590e562cc6d28133de24f4ce2c78ed70aa6b2"
img_url="https://picodemo.s3.us-west-2.amazonaws.com/reth-elf-new"
input_url="https://picodemo.s3.us-west-2.amazonaws.com/reth_input_24165764.bin"
input_data="0x"
max_fee="1000000000000000000"
min_stake="1000000000000000000000"
deadline=1767627013 # note, should be a future time in less than 30 days
version=0 # pico verifier version, default to 0

# for refund command
[refund]
req_ids = []

# for init-prover command
[init_prover]
submitter_keystore=""
submitter_passphrase=""
prover_name=""
prover_icon=""

# for stake command
[stake]
stake_to_prover=""
stake_amt="1000000000000000000000"

# for unstake command
[unstake]
unstake_from_prover=""