[chain]
chain_id=421614
chain_rpc="https://arbitrum-sepolia-rpc.publicnode.com"
brevis_market_addr="0x7c968e3b1FaE6599958104cbf40d17A4ba0c1d43"
staking_token_addr="0x46b07178907650afc855763a8f83e65afec24074"
keystore=""
passphrase=""

[[request]]
nonce=10
vk="0x0089f0a410239c6ad22a5bd5b026848fcdb57cc2d5ed860e722dc92fa8df784e"
public_value_digest="0x03b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
img_url="https://github.com/hezhihua81/test/raw/refs/heads/main/fib-elf"
input_url="https://github.com/hezhihua81/test/raw/refs/heads/main/fib.bin"
input_data="0x"
max_fee=10000000000
min_stake=1
deadline=1763784173